# Generated by Django 3.1.7 on 2021-06-19 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=200, null=True)),
                ('correo', models.CharField(max_length=200, null=True)),
                ('contraseña', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200, null=True)),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitoDeUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='01', max_length=200)),
                ('titulo', models.CharField(max_length=200, null=True)),
                ('prioridad', models.CharField(choices=[('Deseable', 'Deseable'), ('No Deseable', 'No Deseable'), ('Critico', 'Critico')], max_length=200, null=True)),
                ('tipe', models.CharField(choices=[('Funcional', 'Funcional'), ('No Funcional', 'No Funcional'), ('Restriccion', 'Restriccion'), ('Calidad', 'Calidad')], max_length=200, null=True)),
                ('fuente', models.CharField(max_length=200, null=True)),
                ('estabilidad', models.CharField(choices=[('Transable', 'Transable'), ('Intransable', 'Intransable')], max_length=200, null=True)),
                ('urgencia', models.CharField(choices=[('Urgente', 'Urgente'), ('Normal', 'Normal'), ('Si se puede', 'Si se puede')], max_length=200, null=True)),
                ('estado', models.CharField(choices=[('Cumple', 'Cumple'), ('No Cumple', 'No Cumple')], max_length=200, null=True)),
                ('costo', models.CharField(max_length=200, null=True)),
                ('descripcion', models.CharField(max_length=400, null=True)),
                ('version', models.CharField(default=1, max_length=200)),
                ('proyecto_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitoDeSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200, null=True)),
                ('titulo', models.CharField(max_length=200, null=True)),
                ('tipe', models.CharField(choices=[('Funcional', 'Funcional'), ('No Funcional', 'No Funcional'), ('Restriccion', 'Restriccion'), ('Calidad', 'Calidad')], max_length=200, null=True)),
                ('costo', models.CharField(max_length=200, null=True)),
                ('urgencia', models.CharField(choices=[('Urgente', 'Urgente'), ('Normal', 'Normal'), ('Si se puede', 'Si se puede')], max_length=200, null=True)),
                ('estado', models.CharField(choices=[('Cumple', 'Cumple'), ('No Cumple', 'No Cumple')], max_length=200, null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('version', models.CharField(default=1, max_length=200)),
                ('proyecto_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.proyecto')),
                ('requisito_usuario_codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.requisitodeusuario')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cuenta')),
                ('proyecto_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='AnalizisRu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_analisis_ru', models.IntegerField(default=1)),
                ('smell_codigo', models.CharField(max_length=200, null=True)),
                ('ru_codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.requisitodeusuario')),
            ],
        ),
        migrations.CreateModel(
            name='AnalizisRs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_analisis_rs', models.IntegerField(default=1)),
                ('smell_codigo', models.CharField(max_length=200, null=True)),
                ('rs_codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.requisitodesistema')),
            ],
        ),
    ]
