# Generated by Django 3.1.7 on 2021-06-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210619_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analizisrs',
            name='id_analisis_rs',
        ),
        migrations.RemoveField(
            model_name='analizisru',
            name='id_analisis_ru',
        ),
        migrations.RemoveField(
            model_name='requisitodesistema',
            name='id',
        ),
        migrations.AlterField(
            model_name='requisitodesistema',
            name='codigo',
            field=models.AutoField(default='RS01', primary_key=True, serialize=False),
        ),
    ]
