# Generated by Django 3.1.7 on 2021-07-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210629_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmellDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smell_codigo', models.CharField(max_length=200, null=True)),
                ('smell_titulo', models.CharField(max_length=200, null=True)),
                ('smell_descripcion', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='analizisrs',
            options={'verbose_name': 'Analisis RS'},
        ),
        migrations.AlterModelOptions(
            name='analizisru',
            options={'verbose_name': 'Analisis RU'},
        ),
    ]
