# Generated by Django 3.2.7 on 2021-09-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_proyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Completado', 'Completado')], max_length=200, null=True),
        ),
    ]
