# Generated by Django 3.2.7 on 2021-10-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_proyecto_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisitodesistema',
            old_name='tipe',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='requisitodeusuario',
            old_name='tipe',
            new_name='tipo',
        ),
    ]
