# Generated by Django 3.2.7 on 2021-11-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='admin',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
