# Generated by Django 3.2.7 on 2022-03-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211201_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='analizisrs',
            name='version',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='analizisru',
            name='version',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
