# Generated by Django 3.2.7 on 2022-03-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220324_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analizisrs',
            name='smell_codigo',
            field=models.CharField(default=' ', max_length=700),
        ),
        migrations.AlterField(
            model_name='analizisru',
            name='smell_codigo',
            field=models.CharField(default=' ', max_length=700),
        ),
    ]
