# Generated by Django 3.2.7 on 2022-04-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_analisisrudesc_analizisrsdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitodeusuario',
            name='descripcion',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='requisitosistema',
            name='descripcion',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
