# Generated by Django 3.2.7 on 2022-04-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220403_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisrudesc',
            name='feedback',
            field=models.CharField(default=' ', max_length=800),
        ),
        migrations.AddField(
            model_name='analizisrs',
            name='feedback',
            field=models.CharField(default=' ', max_length=800),
        ),
        migrations.AddField(
            model_name='analizisrsdesc',
            name='feedback',
            field=models.CharField(default=' ', max_length=800),
        ),
        migrations.AddField(
            model_name='analizisru',
            name='feedback',
            field=models.CharField(default=' ', max_length=800),
        ),
    ]
